name: CI

on:
  push:
    branches:
      - master
      - development
      - 2.0
  pull_request:
    branches:
      - "*"

jobs:
  typecheck_tests:
    name: Typecheck tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-node@v1
        with:
          node-version: 10
      - uses: actions/checkout@v2
      - name: Install node-gyp-cache
        run: |
          yarn global add node-gyp-cache
          yarn config set node_gyp node-gyp-cache
      - name: Install
        run: yarn --frozen-lockfile
      - name: Build tests
        run: yarn build-test
